# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo $sourceVersion
        commitHash=${sourceVersion:0:7}
        echo $commitHash
        echo "##vso[task.setvariable variable=commitHash]$commitHash"
      env: { sourceVersion: $(Build.SourceVersion) }
      displayName: Git Hash 7-digit
      workingDirectory: $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'Christian Hernandez Dockerhub'
    - task: Docker@2
      displayName: Build and push container
      inputs:
        containerRegistry: 'Christian Hernandez Dockerhub'
        repository: 'christianh814/demo-gobg'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(commitHash)
          latest
