# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
    - main

resources:
- repo: self  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: KubectlInstaller@0
      displayName: Install Kubernetes support tools
      inputs:
        kubectlVersion: 1.28.2
    - script: |
        echo $sourceVersion
        commitHash=${sourceVersion:0:7}
        echo $commitHash
        echo "##vso[task.setvariable variable=commitHash]$commitHash"
      env: { sourceVersion: $(Build.SourceVersion) }
      displayName: Git Hash 7-digit
      workingDirectory: $(Build.SourcesDirectory)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'Christian Hernandez Dockerhub'
    - task: Docker@2
      displayName: Build and push container
      inputs:
        containerRegistry: 'Christian Hernandez Dockerhub'
        repository: 'christianh814/demo-gobg'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(commitHash)
          latest
    - script: |
        AUTH=$(githubPAT)
        git clone https://christianh814:${AUTH}@github.com/christianh814/demo-deploy-gobg
        cd ./demo-deploy-gobg/deploy/overlays/dev/
        kustomize edit set image christianh814/demo-gobg:$(commitHash)
        git add -A .
        git commit -am "Update image to $(commitHash)"
        git push origin main
        cd -
      displayName: Clone deployment repo and commit to dev overlay
      workingDirectory: $(Build.SourcesDirectory)
    - script: |
        tree demo-deploy-gobg
      displayName: checking dir
      workingDirectory: $(Build.SourcesDirectory)